import java.util.HashMap;
import java.util.ArrayList;
import env3d.advanced.EnvNode;
/**
 * This class is generated by the env3d plugin to make
 * it easier to work with models.  It scans a model
 * directory for all the obj files and organized them.
 */
public class LongHouse extends GameObject
{
    private EnvNode debugNode1;
    private EnvNode debugNode2;
    
    private EnvNode[] collisionNode;
    /**
     * Zero-argument constructor that places the object in location 0, 0, 0
     */
    public LongHouse()
    {
        this(0,0,0);
    }

    /**
     * Parameterized constructor - allows arbitary of object
     */
    public LongHouse(double x, double y, double z)
    {
        setX(x);
        setY(y);
        setZ(z);
        setScale(1);
        setTexture("models/longHouse/HouseLong.png");
        setModel("models/longHouse/LongHouse.obj");
    }

    public void move() 
    {
        // Create nodes for collision purposes -- these are not visible.        
        if (collisionNode == null) {
            collisionNode = new EnvNode[3];
            double scale = 3;
            for (int i = 0; i < 3; i++) {
                collisionNode[i] = new EnvNode();
                collisionNode[i].setX(this.getX()-scale*Math.cos(Math.toRadians(this.getRotateY())));
                collisionNode[i].setY(1);
                collisionNode[i].setZ(this.getZ()+scale*Math.sin(Math.toRadians(this.getRotateY())));
                collisionNode[i].setScale(4);
                scale -= 3;
                // for debugging purpose, you can make the nodes visible
                // env.addObject(collisionNode[i]);
            }
        }
        
        // Check every actor for collision
        for (Actor z : getEnv().getObjects(Actor.class)) {   
            for (EnvNode cNode : collisionNode) {
                if (z.distance(cNode) < cNode.getScale()+z.getScale()) {
                    if (z instanceof Zombie) {
                        z.moveForward(-0.1);
                        z.setRotateY(z.getRotateY()+180);
                    } else if (z instanceof Hunter) {
                        ((Hunter) z).revert();
                    }
                }
            }
        }
        
    }
}
